### ISSUE TITLE
Encoding a keystore with private key produces unrecoverable keys

### ISSUE THREAD

**Issue by jimmidyson** [pavel-v-chernykh/keystore-go#3]
Great library btw - thanks for creating it!

Tried out the keystore produced in pem example & can't recover the private key:

```
Exception in thread "main" java.security.UnrecoverableKeyException: version mismatch: (supported:     00, parsed:     01
  at sun.security.provider.KeyProtector.recover(KeyProtector.java:338)
  at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:146)
  at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
  at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
  at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
  at java.security.KeyStore.getKey(KeyStore.java:1023)
  at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
  at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
  at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
  at Server.main(Server.java:27)
```

Trying to create a key manager throws this exception when referencing the keystore that the example produces, example code:

```java
KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
kmf.init(keystore, keypass);
```

Any ideas?

**Comment by jimmidyson** [comment]
Even simpler code, just trying to get Key from keystore:

```java
public static void main(String[] args) {
    char[] storepass = "password".toCharArray();
    char[] keypass = "password".toCharArray();
    String alias = "server";
    FileInputStream fIn = new FileInputStream("keystore.jks");
    KeyStore keystore = KeyStore.getInstance("JKS");
    keystore.load(fIn, storepass);
    // display certificate
    Certificate cert = keystore.getCertificate(alias);
    System.out.println(cert);
    Key key = keystore.getKey(alias, keypass);
    System.out.println(key);
}
```

**Comment by jimmidyson** [comment]
And via keytool converting shows a different error:

```bash
keytool -importkeystore -srckeystore examples/pem/keystore.jks -destkeystore new-store.jks

Enter destination keystore password:  
Re-enter new password: 
Enter source keystore password:  
Enter key password for <alias>
keytool error: java.security.UnrecoverableKeyException: algid parse error, not a sequence
```

**Comment by jimmidyson** [comment]
So I think it looks like the private key actually needs to be pkcs8 encoded, not pkcs1. Perhaps.

**Comment by jimmidyson** [comment]
No don't think that's it. Out of ideas now... help appreciated!

**Comment by jimmidyson** [comment]
Ah yes, converting to PKCS8 works for me. Wonder if that should be mentioned in the README & possibly a utility provided to do the conversion from PKCS1 to PKCS8 (there's nothing in the standard library - had to use a hacked/updated version of https://github.com/youmark/pkcs8

**Comment by pavel-v-chernykh** [comment]
Hi, @jimmidyson 

> Great library btw - thanks for creating it!

You are welcome!

You are right JKS format assumes that private keys are PKCS8 encoded.
Thanks for pointing on that oversight.

I updated the ```pem``` example and README file with some notes about that.

**Comment by jimmidyson** [comment]
LGTM thanks!
